HeaderQuery = "HeaderQuery"
PositionQuery = 'PositionQuery'
UploadDirectory = 'UploadDirectory'
ExchangePeriod = 'ExchangePeriod'
ExchangeType = 'ExchangeType'
dbPath = 'dbPath'
lastExportTime='lastExportTime'
apiKey='apiKey'
FbClientPath='FbClientPath'